#!/bin/bash

# Declare Variables ###############################
red='\033[1;31m'
grn='\033[1;32m'
yel='\033[1;33m'
blu='\033[1;36m'
pnk='\033[1;35m'
clr='\033[0m'

echo -ne "${grn} getting external IP address... ";
EXTERNAL_HOST_IP=$(curl -s https://api.ipify.org)
echo -e "${yel}$EXTERNAL_HOST_IP ${clr}";

DAGDIR=$HOME/constellation

function checkCert()
{
  if [ ! -f "*.p12" ]; then
    echo -e "${red} Certification File not found! ${yel}Please make sure you download your .p12 file here before running the installer!${clr}"
    echo -e "${red} Installation Aborted."
    echo
    exit 1
  fi
}



# BEGIN ###############################
checkCert
